name: build

on: [push]

jobs:

    build:
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          echo "tag=${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          if [ ${{ endsWith(github.ref, '-lts') }} = true ]; then
            echo "tag_latest=latest-lts,latest-${GITHUB_REF:11:4}-lts" >>$GITHUB_OUTPUT
          else
            echo "tag_latest=latest" >>$GITHUB_OUTPUT
          fi

      - name: Build and publish docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        if: github.event_name != 'pull_request'
        with:
          name: sourcepole/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }},${{ steps.get_tag.outputs.tag_latest }},${{ steps.get_tag.outputs.tag }}-noqgis,${{ steps.get_tag.outputs.tag_latest }}-noqgis"
